<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'AF',
                'name' => 'Afghanistan',
                'phonecode' => '93',
                'flag' => '/flags/flag-of-Afghanistan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:25:38',
                'default_currency' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'AL',
                'name' => 'Albania',
                'phonecode' => '355',
                'flag' => '/flags/flag-of-Albania.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-02-08 20:55:12',
                'default_currency' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'DZ',
                'name' => 'Algeria',
                'phonecode' => '213',
                'flag' => '/flags/flag-of-Algeria.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'AS',
                'name' => 'American Samoa',
                'phonecode' => '1684',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'AD',
                'name' => 'Andorra',
                'phonecode' => '376',
                'flag' => '/flags/flag-of-Andorra.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:25:29',
                'default_currency' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'AO',
                'name' => 'Angola',
                'phonecode' => '244',
                'flag' => '/flags/flag-of-Angola.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'AI',
                'name' => 'Anguilla',
                'phonecode' => '1264',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'AQ',
                'name' => 'Antarctica',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'AG',
                'name' => 'Antigua And Barbuda',
                'phonecode' => '1268',
                'flag' => '/flags/flag-of-Antigua.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:25:42',
                'default_currency' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'AR',
                'name' => 'Argentina',
                'phonecode' => '54',
                'flag' => '/flags/flag-of-Argentina.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'AM',
                'name' => 'Armenia',
                'phonecode' => '374',
                'flag' => '/flags/flag-of-Armenia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'AW',
                'name' => 'Aruba',
                'phonecode' => '297',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'AU',
                'name' => 'Australia',
                'phonecode' => '61',
                'flag' => '/flags/flag-of-Australia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'AT',
                'name' => 'Austria',
                'phonecode' => '43',
                'flag' => '/flags/flag-of-Austria.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'AZ',
                'name' => 'Azerbaijan',
                'phonecode' => '994',
                'flag' => '/flags/flag-of-Azerbaijan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'BS',
                'name' => 'Bahamas The',
                'phonecode' => '1242',
                'flag' => '/flags/flag-of-Bahamas.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'BH',
                'name' => 'Bahrain',
                'phonecode' => '973',
                'flag' => '/flags/flag-of-Bahrain.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:26:13',
                'default_currency' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'BD',
                'name' => 'Bangladesh',
                'phonecode' => '880',
                'flag' => '/flags/flag-of-Bangladesh.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'BB',
                'name' => 'Barbados',
                'phonecode' => '1246',
                'flag' => '/flags/flag-of-Barbados.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'BY',
                'name' => 'Belarus',
                'phonecode' => '375',
                'flag' => '/flags/flag-of-Belarus.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'BE',
                'name' => 'Belgium',
                'phonecode' => '32',
                'flag' => '/flags/flag-of-Belgium.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'BZ',
                'name' => 'Belize',
                'phonecode' => '501',
                'flag' => '/flags/flag-of-Belize.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'BJ',
                'name' => 'Benin',
                'phonecode' => '229',
                'flag' => '/flags/flag-of-Benin.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'BM',
                'name' => 'Bermuda',
                'phonecode' => '1441',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'BT',
                'name' => 'Bhutan',
                'phonecode' => '975',
                'flag' => '/flags/flag-of-Bhutan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'BO',
                'name' => 'Bolivia',
                'phonecode' => '591',
                'flag' => '/flags/flag-of-Bolivia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'phonecode' => '387',
                'flag' => '/flags/flag-of-Bosnia-Herzegovina.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'BW',
                'name' => 'Botswana',
                'phonecode' => '267',
                'flag' => '/flags/flag-of-Botswana.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'BV',
                'name' => 'Bouvet Island',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'BR',
                'name' => 'Brazil',
                'phonecode' => '55',
                'flag' => '/flags/flag-of-Brazil.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:26:44',
                'default_currency' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'IO',
                'name' => 'British Indian Ocean Territory',
                'phonecode' => '246',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'BN',
                'name' => 'Brunei',
                'phonecode' => '673',
                'flag' => '/flags/flag-of-Brunei.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'BG',
                'name' => 'Bulgaria',
                'phonecode' => '359',
                'flag' => '/flags/flag-of-Bulgaria.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'phonecode' => '226',
                'flag' => '/flags/flag-of-Burkina-Faso.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'BI',
                'name' => 'Burundi',
                'phonecode' => '257',
                'flag' => '/flags/flag-of-Burundi.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'KH',
                'name' => 'Cambodia',
                'phonecode' => '855',
                'flag' => '/flags/flag-of-Cambodia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'CM',
                'name' => 'Cameroon',
                'phonecode' => '237',
                'flag' => '/flags/flag-of-Cameroon.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'CA',
                'name' => 'Canada',
                'phonecode' => '1',
                'flag' => '/flags/flag-of-Canada.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'CV',
                'name' => 'Cape Verde',
                'phonecode' => '238',
                'flag' => '/flags/flag-of-Cabo-Verde.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'KY',
                'name' => 'Cayman Islands',
                'phonecode' => '1345',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'CF',
                'name' => 'Central African Republic',
                'phonecode' => '236',
                'flag' => '/flags/flag-of-Central-African-Republic.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'TD',
                'name' => 'Chad',
                'phonecode' => '235',
                'flag' => '/flags/flag-of-Chad.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'CL',
                'name' => 'Chile',
                'phonecode' => '56',
                'flag' => '/flags/flag-of-Chile.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'CN',
                'name' => 'China',
                'phonecode' => '86',
                'flag' => '/flags/flag-of-China.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'CX',
                'name' => 'Christmas Island',
                'phonecode' => '61',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'CC',
            'name' => 'Cocos (Keeling) Islands',
                'phonecode' => '672',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'CO',
                'name' => 'Colombia',
                'phonecode' => '57',
                'flag' => '/flags/flag-of-Colombia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'KM',
                'name' => 'Comoros',
                'phonecode' => '269',
                'flag' => '/flags/flag-of-Comoros.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'CG',
                'name' => 'Republic Of The Congo',
                'phonecode' => '242',
                'flag' => '/flags/flag-of-Congo.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'CD',
                'name' => 'Democratic Republic Of The Congo',
                'phonecode' => '242',
                'flag' => '/flags/flag-of-Congo-Democratic-Republic-of.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'CK',
                'name' => 'Cook Islands',
                'phonecode' => '682',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'CR',
                'name' => 'Costa Rica',
                'phonecode' => '506',
                'flag' => '/flags/flag-of-Costa-Rica.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'CI',
            'name' => 'Cote D\'Ivoire (Ivory Coast)',
                'phonecode' => '225',
                'flag' => '/flags/flag-of-Cote-d-Ivoire.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'HR',
            'name' => 'Croatia (Hrvatska)',
                'phonecode' => '385',
                'flag' => '/flags/flag-of-Croatia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'CU',
                'name' => 'Cuba',
                'phonecode' => '53',
                'flag' => '/flags/flag-of-Cuba.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'CY',
                'name' => 'Cyprus',
                'phonecode' => '357',
                'flag' => '/flags/flag-of-Cyprus.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'phonecode' => '420',
                'flag' => '/flags/flag-of-Czech-Republic.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'DK',
                'name' => 'Denmark',
                'phonecode' => '45',
                'flag' => '/flags/flag-of-Denmark.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'DJ',
                'name' => 'Djibouti',
                'phonecode' => '253',
                'flag' => '/flags/flag-of-Djibouti.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'DM',
                'name' => 'Dominica',
                'phonecode' => '1767',
                'flag' => '/flags/flag-of-Dominica.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'DO',
                'name' => 'Dominican Republic',
                'phonecode' => '1809',
                'flag' => '/flags/flag-of-Dominican-Republic.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'TP',
                'name' => 'East Timor',
                'phonecode' => '670',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'EC',
                'name' => 'Ecuador',
                'phonecode' => '593',
                'flag' => '/flags/flag-of-Ecuador.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'EG',
                'name' => 'Egypt',
                'phonecode' => '20',
                'flag' => '/flags/flag-of-Egypt.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-04-17 19:12:27',
                'default_currency' => 3,
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'SV',
                'name' => 'El Salvador',
                'phonecode' => '503',
                'flag' => '/flags/flag-of-El-Salvador.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'GQ',
                'name' => 'Equatorial Guinea',
                'phonecode' => '240',
                'flag' => '/flags/flag-of-Equatorial-Guinea.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'ER',
                'name' => 'Eritrea',
                'phonecode' => '291',
                'flag' => '/flags/flag-of-Eritrea.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'EE',
                'name' => 'Estonia',
                'phonecode' => '372',
                'flag' => '/flags/flag-of-Estonia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'ET',
                'name' => 'Ethiopia',
                'phonecode' => '251',
                'flag' => '/flags/flag-of-Ethiopia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'XA',
                'name' => 'External Territories of Australia',
                'phonecode' => '61',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'FK',
                'name' => 'Falkland Islands',
                'phonecode' => '500',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 'FO',
                'name' => 'Faroe Islands',
                'phonecode' => '298',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 'FJ',
                'name' => 'Fiji Islands',
                'phonecode' => '679',
                'flag' => '/flags/flag-of-Fiji.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'code' => 'FI',
                'name' => 'Finland',
                'phonecode' => '358',
                'flag' => '/flags/flag-of-Finland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            74 => 
            array (
                'id' => 75,
                'code' => 'FR',
                'name' => 'France',
                'phonecode' => '33',
                'flag' => '/flags/flag-of-France.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            75 => 
            array (
                'id' => 76,
                'code' => 'GF',
                'name' => 'French Guiana',
                'phonecode' => '594',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'code' => 'PF',
                'name' => 'French Polynesia',
                'phonecode' => '689',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            77 => 
            array (
                'id' => 78,
                'code' => 'TF',
                'name' => 'French Southern Territories',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'code' => 'GA',
                'name' => 'Gabon',
                'phonecode' => '241',
                'flag' => '/flags/flag-of-Gabon.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'code' => 'GM',
                'name' => 'Gambia The',
                'phonecode' => '220',
                'flag' => '/flags/flag-of-Gambia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 'GE',
                'name' => 'Georgia',
                'phonecode' => '995',
                'flag' => '/flags/flag-of-Georgia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            81 => 
            array (
                'id' => 82,
                'code' => 'DE',
                'name' => 'Germany',
                'phonecode' => '49',
                'flag' => '/flags/flag-of-Germany.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            82 => 
            array (
                'id' => 83,
                'code' => 'GH',
                'name' => 'Ghana',
                'phonecode' => '233',
                'flag' => '/flags/flag-of-Ghana.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'code' => 'GI',
                'name' => 'Gibraltar',
                'phonecode' => '350',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            84 => 
            array (
                'id' => 85,
                'code' => 'GR',
                'name' => 'Greece',
                'phonecode' => '30',
                'flag' => '/flags/flag-of-Greece.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            85 => 
            array (
                'id' => 86,
                'code' => 'GL',
                'name' => 'Greenland',
                'phonecode' => '299',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'code' => 'GD',
                'name' => 'Grenada',
                'phonecode' => '1473',
                'flag' => '/flags/flag-of-Grenada.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'code' => 'GP',
                'name' => 'Guadeloupe',
                'phonecode' => '590',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            88 => 
            array (
                'id' => 89,
                'code' => 'GU',
                'name' => 'Guam',
                'phonecode' => '1671',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'code' => 'GT',
                'name' => 'Guatemala',
                'phonecode' => '502',
                'flag' => '/flags/flag-of-Guatemala.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'code' => 'XU',
                'name' => 'Guernsey and Alderney',
                'phonecode' => '44',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            91 => 
            array (
                'id' => 92,
                'code' => 'GN',
                'name' => 'Guinea',
                'phonecode' => '224',
                'flag' => '/flags/flag-of-Guinea.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'code' => 'GW',
                'name' => 'Guinea-Bissau',
                'phonecode' => '245',
                'flag' => '/flags/flag-of-Guinea-Bissau.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'code' => 'GY',
                'name' => 'Guyana',
                'phonecode' => '592',
                'flag' => '/flags/flag-of-Guyana.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            94 => 
            array (
                'id' => 95,
                'code' => 'HT',
                'name' => 'Haiti',
                'phonecode' => '509',
                'flag' => '/flags/flag-of-Haiti.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            95 => 
            array (
                'id' => 96,
                'code' => 'HM',
                'name' => 'Heard and McDonald Islands',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'code' => 'HN',
                'name' => 'Honduras',
                'phonecode' => '504',
                'flag' => '/flags/flag-of-Honduras.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            97 => 
            array (
                'id' => 98,
                'code' => 'HK',
                'name' => 'Hong Kong S.A.R.',
                'phonecode' => '852',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            98 => 
            array (
                'id' => 99,
                'code' => 'HU',
                'name' => 'Hungary',
                'phonecode' => '36',
                'flag' => '/flags/flag-of-Hungary.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            99 => 
            array (
                'id' => 100,
                'code' => 'IS',
                'name' => 'Iceland',
                'phonecode' => '354',
                'flag' => '/flags/flag-of-Iceland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            100 => 
            array (
                'id' => 101,
                'code' => 'IN',
                'name' => 'India',
                'phonecode' => '91',
                'flag' => '/flags/flag-of-India.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            101 => 
            array (
                'id' => 102,
                'code' => 'ID',
                'name' => 'Indonesia',
                'phonecode' => '62',
                'flag' => '/flags/flag-of-Indonesia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'code' => 'IR',
                'name' => 'Iran',
                'phonecode' => '98',
                'flag' => '/flags/flag-of-Iran.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            103 => 
            array (
                'id' => 104,
                'code' => 'IQ',
                'name' => 'Iraq',
                'phonecode' => '964',
                'flag' => '/flags/flag-of-Iraq.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            104 => 
            array (
                'id' => 105,
                'code' => 'IE',
                'name' => 'Ireland',
                'phonecode' => '353',
                'flag' => '/flags/flag-of-Ireland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            105 => 
            array (
                'id' => 106,
                'code' => 'IL',
                'name' => 'Israel',
                'phonecode' => '972',
                'flag' => '/flags/flag-of-Israel.jpg',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => '2022-07-17 00:32:01',
                'default_currency' => 1,
            ),
            106 => 
            array (
                'id' => 107,
                'code' => 'IT',
                'name' => 'Italy',
                'phonecode' => '39',
                'flag' => '/flags/flag-of-Italy.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            107 => 
            array (
                'id' => 108,
                'code' => 'JM',
                'name' => 'Jamaica',
                'phonecode' => '1876',
                'flag' => '/flags/flag-of-Jamaica.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            108 => 
            array (
                'id' => 109,
                'code' => 'JP',
                'name' => 'Japan',
                'phonecode' => '81',
                'flag' => '/flags/flag-of-Japan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            109 => 
            array (
                'id' => 110,
                'code' => 'XJ',
                'name' => 'Jersey',
                'phonecode' => '44',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            110 => 
            array (
                'id' => 111,
                'code' => 'JO',
                'name' => 'Jordan',
                'phonecode' => '962',
                'flag' => '/flags/flag-of-Jordan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            111 => 
            array (
                'id' => 112,
                'code' => 'KZ',
                'name' => 'Kazakhstan',
                'phonecode' => '7',
                'flag' => '/flags/flag-of-Kazakhstan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'code' => 'KE',
                'name' => 'Kenya',
                'phonecode' => '254',
                'flag' => '/flags/flag-of-Kenya.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            113 => 
            array (
                'id' => 114,
                'code' => 'KI',
                'name' => 'Kiribati',
                'phonecode' => '686',
                'flag' => '/flags/flag-of-Kiribati.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            114 => 
            array (
                'id' => 115,
                'code' => 'KP',
                'name' => 'Korea North',
                'phonecode' => '850',
                'flag' => '/flags/flag-of-Korea-North.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            115 => 
            array (
                'id' => 116,
                'code' => 'KR',
                'name' => 'Korea South',
                'phonecode' => '82',
                'flag' => '/flags/flag-of-Korea-South.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            116 => 
            array (
                'id' => 117,
                'code' => 'KW',
                'name' => 'Kuwait',
                'phonecode' => '965',
                'flag' => '/flags/flag-of-Kuwait.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'code' => 'KG',
                'name' => 'Kyrgyzstan',
                'phonecode' => '996',
                'flag' => '/flags/flag-of-Kyrgyzstan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            118 => 
            array (
                'id' => 119,
                'code' => 'LA',
                'name' => 'Laos',
                'phonecode' => '856',
                'flag' => '/flags/flag-of-Laos.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'code' => 'LV',
                'name' => 'Latvia',
                'phonecode' => '371',
                'flag' => '/flags/flag-of-Latvia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            120 => 
            array (
                'id' => 121,
                'code' => 'LB',
                'name' => 'Lebanon',
                'phonecode' => '961',
                'flag' => '/flags/flag-of-Lebanon.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            121 => 
            array (
                'id' => 122,
                'code' => 'LS',
                'name' => 'Lesotho',
                'phonecode' => '266',
                'flag' => '/flags/flag-of-Lesotho.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            122 => 
            array (
                'id' => 123,
                'code' => 'LR',
                'name' => 'Liberia',
                'phonecode' => '231',
                'flag' => '/flags/flag-of-Liberia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            123 => 
            array (
                'id' => 124,
                'code' => 'LY',
                'name' => 'Libya',
                'phonecode' => '218',
                'flag' => '/flags/flag-of-Libya.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            124 => 
            array (
                'id' => 125,
                'code' => 'LI',
                'name' => 'Liechtenstein',
                'phonecode' => '423',
                'flag' => '/flags/flag-of-Liechtenstein.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            125 => 
            array (
                'id' => 126,
                'code' => 'LT',
                'name' => 'Lithuania',
                'phonecode' => '370',
                'flag' => '/flags/flag-of-Lithuania.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            126 => 
            array (
                'id' => 127,
                'code' => 'LU',
                'name' => 'Luxembourg',
                'phonecode' => '352',
                'flag' => '/flags/flag-of-Luxembourg.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            127 => 
            array (
                'id' => 128,
                'code' => 'MO',
                'name' => 'Macau S.A.R.',
                'phonecode' => '853',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            128 => 
            array (
                'id' => 129,
                'code' => 'MK',
                'name' => 'Macedonia',
                'phonecode' => '389',
                'flag' => '/flags/flag-of-Macedonia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            129 => 
            array (
                'id' => 130,
                'code' => 'MG',
                'name' => 'Madagascar',
                'phonecode' => '261',
                'flag' => '/flags/flag-of-Madagascar.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            130 => 
            array (
                'id' => 131,
                'code' => 'MW',
                'name' => 'Malawi',
                'phonecode' => '265',
                'flag' => '/flags/flag-of-Malawi.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            131 => 
            array (
                'id' => 132,
                'code' => 'MY',
                'name' => 'Malaysia',
                'phonecode' => '60',
                'flag' => '/flags/flag-of-Malaysia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            132 => 
            array (
                'id' => 133,
                'code' => 'MV',
                'name' => 'Maldives',
                'phonecode' => '960',
                'flag' => '/flags/flag-of-Maldives.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            133 => 
            array (
                'id' => 134,
                'code' => 'ML',
                'name' => 'Mali',
                'phonecode' => '223',
                'flag' => '/flags/flag-of-Mali.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            134 => 
            array (
                'id' => 135,
                'code' => 'MT',
                'name' => 'Malta',
                'phonecode' => '356',
                'flag' => '/flags/flag-of-Malta.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            135 => 
            array (
                'id' => 136,
                'code' => 'XM',
            'name' => 'Man (Isle of)',
                'phonecode' => '44',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            136 => 
            array (
                'id' => 137,
                'code' => 'MH',
                'name' => 'Marshall Islands',
                'phonecode' => '692',
                'flag' => '/flags/flag-of-Marshall-Islands.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            137 => 
            array (
                'id' => 138,
                'code' => 'MQ',
                'name' => 'Martinique',
                'phonecode' => '596',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            138 => 
            array (
                'id' => 139,
                'code' => 'MR',
                'name' => 'Mauritania',
                'phonecode' => '222',
                'flag' => '/flags/flag-of-Mauritania.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            139 => 
            array (
                'id' => 140,
                'code' => 'MU',
                'name' => 'Mauritius',
                'phonecode' => '230',
                'flag' => '/flags/flag-of-Mauritius.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            140 => 
            array (
                'id' => 141,
                'code' => 'YT',
                'name' => 'Mayotte',
                'phonecode' => '269',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            141 => 
            array (
                'id' => 142,
                'code' => 'MX',
                'name' => 'Mexico',
                'phonecode' => '52',
                'flag' => '/flags/flag-of-Mexico.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            142 => 
            array (
                'id' => 143,
                'code' => 'FM',
                'name' => 'Micronesia',
                'phonecode' => '691',
                'flag' => '/flags/flag-of-Micronesia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            143 => 
            array (
                'id' => 144,
                'code' => 'MD',
                'name' => 'Moldova',
                'phonecode' => '373',
                'flag' => '/flags/flag-of-Moldova.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            144 => 
            array (
                'id' => 145,
                'code' => 'MC',
                'name' => 'Monaco',
                'phonecode' => '377',
                'flag' => '/flags/flag-of-Monaco.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            145 => 
            array (
                'id' => 146,
                'code' => 'MN',
                'name' => 'Mongolia',
                'phonecode' => '976',
                'flag' => '/flags/flag-of-Mongolia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            146 => 
            array (
                'id' => 147,
                'code' => 'MS',
                'name' => 'Montserrat',
                'phonecode' => '1664',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            147 => 
            array (
                'id' => 148,
                'code' => 'MA',
                'name' => 'Morocco',
                'phonecode' => '212',
                'flag' => '/flags/flag-of-Morocco.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            148 => 
            array (
                'id' => 149,
                'code' => 'MZ',
                'name' => 'Mozambique',
                'phonecode' => '258',
                'flag' => '/flags/flag-of-Mozambique.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            149 => 
            array (
                'id' => 150,
                'code' => 'MM',
                'name' => 'Myanmar',
                'phonecode' => '95',
                'flag' => '/flags/flag-of-Myanmar.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            150 => 
            array (
                'id' => 151,
                'code' => 'NA',
                'name' => 'Namibia',
                'phonecode' => '264',
                'flag' => '/flags/flag-of-Namibia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            151 => 
            array (
                'id' => 152,
                'code' => 'NR',
                'name' => 'Nauru',
                'phonecode' => '674',
                'flag' => '/flags/flag-of-Nauru.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            152 => 
            array (
                'id' => 153,
                'code' => 'NP',
                'name' => 'Nepal',
                'phonecode' => '977',
                'flag' => '/flags/flag-of-Nepal.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            153 => 
            array (
                'id' => 154,
                'code' => 'AN',
                'name' => 'Netherlands Antilles',
                'phonecode' => '599',
                'flag' => '/flags/flag-of-Netherlands.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            154 => 
            array (
                'id' => 155,
                'code' => 'NL',
                'name' => 'Netherlands The',
                'phonecode' => '31',
                'flag' => '/flags/flag-of-Netherlands.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            155 => 
            array (
                'id' => 156,
                'code' => 'NC',
                'name' => 'New Caledonia',
                'phonecode' => '687',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-01-08 15:28:32',
                'default_currency' => 1,
            ),
            156 => 
            array (
                'id' => 157,
                'code' => 'NZ',
                'name' => 'New Zealand',
                'phonecode' => '64',
                'flag' => '/flags/flag-of-New-Zealand.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            157 => 
            array (
                'id' => 158,
                'code' => 'NI',
                'name' => 'Nicaragua',
                'phonecode' => '505',
                'flag' => '/flags/flag-of-Nicaragua.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            158 => 
            array (
                'id' => 159,
                'code' => 'NE',
                'name' => 'Niger',
                'phonecode' => '227',
                'flag' => '/flags/flag-of-Niger.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            159 => 
            array (
                'id' => 160,
                'code' => 'NG',
                'name' => 'Nigeria',
                'phonecode' => '234',
                'flag' => '/flags/flag-of-Nigeria.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            160 => 
            array (
                'id' => 161,
                'code' => 'NU',
                'name' => 'Niue',
                'phonecode' => '683',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            161 => 
            array (
                'id' => 162,
                'code' => 'NF',
                'name' => 'Norfolk Island',
                'phonecode' => '672',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            162 => 
            array (
                'id' => 163,
                'code' => 'MP',
                'name' => 'Northern Mariana Islands',
                'phonecode' => '1670',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            163 => 
            array (
                'id' => 164,
                'code' => 'NO',
                'name' => 'Norway',
                'phonecode' => '47',
                'flag' => '/flags/flag-of-Norway.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            164 => 
            array (
                'id' => 165,
                'code' => 'OM',
                'name' => 'Oman',
                'phonecode' => '968',
                'flag' => '/flags/flag-of-Oman.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            165 => 
            array (
                'id' => 166,
                'code' => 'PK',
                'name' => 'Pakistan',
                'phonecode' => '92',
                'flag' => '/flags/flag-of-Pakistan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            166 => 
            array (
                'id' => 167,
                'code' => 'PW',
                'name' => 'Palau',
                'phonecode' => '680',
                'flag' => '/flags/flag-of-Palau.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            167 => 
            array (
                'id' => 168,
                'code' => 'PS',
                'name' => 'Palestinian Territory Occupied',
                'phonecode' => '970',
                'flag' => '/flags/flag-of-Palestine.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            168 => 
            array (
                'id' => 169,
                'code' => 'PA',
                'name' => 'Panama',
                'phonecode' => '507',
                'flag' => '/flags/flag-of-Panama.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            169 => 
            array (
                'id' => 170,
                'code' => 'PG',
                'name' => 'Papua new Guinea',
                'phonecode' => '675',
                'flag' => '/flags/flag-of-Papua-New-Guinea.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            170 => 
            array (
                'id' => 171,
                'code' => 'PY',
                'name' => 'Paraguay',
                'phonecode' => '595',
                'flag' => '/flags/flag-of-Paraguay.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            171 => 
            array (
                'id' => 172,
                'code' => 'PE',
                'name' => 'Peru',
                'phonecode' => '51',
                'flag' => '/flags/flag-of-Peru.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            172 => 
            array (
                'id' => 173,
                'code' => 'PH',
                'name' => 'Philippines',
                'phonecode' => '63',
                'flag' => '/flags/flag-of-Philippines.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            173 => 
            array (
                'id' => 174,
                'code' => 'PN',
                'name' => 'Pitcairn Island',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            174 => 
            array (
                'id' => 175,
                'code' => 'PL',
                'name' => 'Poland',
                'phonecode' => '48',
                'flag' => '/flags/flag-of-Poland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            175 => 
            array (
                'id' => 176,
                'code' => 'PT',
                'name' => 'Portugal',
                'phonecode' => '351',
                'flag' => '/flags/flag-of-Portugal.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            176 => 
            array (
                'id' => 177,
                'code' => 'PR',
                'name' => 'Puerto Rico',
                'phonecode' => '1787',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            177 => 
            array (
                'id' => 178,
                'code' => 'QA',
                'name' => 'Qatar',
                'phonecode' => '974',
                'flag' => '/flags/flag-of-Qatar.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            178 => 
            array (
                'id' => 179,
                'code' => 'RE',
                'name' => 'Reunion',
                'phonecode' => '262',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            179 => 
            array (
                'id' => 180,
                'code' => 'RO',
                'name' => 'Romania',
                'phonecode' => '40',
                'flag' => '/flags/flag-of-Romania.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            180 => 
            array (
                'id' => 181,
                'code' => 'RU',
                'name' => 'Russia',
                'phonecode' => '70',
                'flag' => '/flags/flag-of-Russia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            181 => 
            array (
                'id' => 182,
                'code' => 'RW',
                'name' => 'Rwanda',
                'phonecode' => '250',
                'flag' => '/flags/flag-of-Rwanda.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            182 => 
            array (
                'id' => 183,
                'code' => 'SH',
                'name' => 'Saint Helena',
                'phonecode' => '290',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            183 => 
            array (
                'id' => 184,
                'code' => 'KN',
                'name' => 'Saint Kitts And Nevis',
                'phonecode' => '1869',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            184 => 
            array (
                'id' => 185,
                'code' => 'LC',
                'name' => 'Saint Lucia',
                'phonecode' => '1758',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            185 => 
            array (
                'id' => 186,
                'code' => 'PM',
                'name' => 'Saint Pierre and Miquelon',
                'phonecode' => '508',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            186 => 
            array (
                'id' => 187,
                'code' => 'VC',
                'name' => 'Saint Vincent And The Grenadines',
                'phonecode' => '1784',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            187 => 
            array (
                'id' => 188,
                'code' => 'WS',
                'name' => 'Samoa',
                'phonecode' => '684',
                'flag' => '/flags/flag-of-Samoa.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            188 => 
            array (
                'id' => 189,
                'code' => 'SM',
                'name' => 'San Marino',
                'phonecode' => '378',
                'flag' => '/flags/flag-of-San-Marino.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            189 => 
            array (
                'id' => 190,
                'code' => 'ST',
                'name' => 'Sao Tome and Principe',
                'phonecode' => '239',
                'flag' => '/flags/flag-of-Sao-Tome-and-Principe.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            190 => 
            array (
                'id' => 191,
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'phonecode' => '966',
                'flag' => '/flags/flag-of-Saudi-Arabia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            191 => 
            array (
                'id' => 192,
                'code' => 'SN',
                'name' => 'Senegal',
                'phonecode' => '221',
                'flag' => '/flags/flag-of-Senegal.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            192 => 
            array (
                'id' => 193,
                'code' => 'RS',
                'name' => 'Serbia',
                'phonecode' => '381',
                'flag' => '/flags/flag-of-Serbia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            193 => 
            array (
                'id' => 194,
                'code' => 'SC',
                'name' => 'Seychelles',
                'phonecode' => '248',
                'flag' => '/flags/flag-of-Seychelles.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            194 => 
            array (
                'id' => 195,
                'code' => 'SL',
                'name' => 'Sierra Leone',
                'phonecode' => '232',
                'flag' => '/flags/flag-of-Sierra-Leone.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            195 => 
            array (
                'id' => 196,
                'code' => 'SG',
                'name' => 'Singapore',
                'phonecode' => '65',
                'flag' => '/flags/flag-of-Singapore.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            196 => 
            array (
                'id' => 197,
                'code' => 'SK',
                'name' => 'Slovakia',
                'phonecode' => '421',
                'flag' => '/flags/flag-of-Slovakia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            197 => 
            array (
                'id' => 198,
                'code' => 'SI',
                'name' => 'Slovenia',
                'phonecode' => '386',
                'flag' => '/flags/flag-of-Slovenia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            198 => 
            array (
                'id' => 199,
                'code' => 'XG',
                'name' => 'Smaller Territories of the UK',
                'phonecode' => '44',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            199 => 
            array (
                'id' => 200,
                'code' => 'SB',
                'name' => 'Solomon Islands',
                'phonecode' => '677',
                'flag' => '/flags/flag-of-Solomon-Islands.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            200 => 
            array (
                'id' => 201,
                'code' => 'SO',
                'name' => 'Somalia',
                'phonecode' => '252',
                'flag' => '/flags/flag-of-Somalia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            201 => 
            array (
                'id' => 202,
                'code' => 'ZA',
                'name' => 'South Africa',
                'phonecode' => '27',
                'flag' => '/flags/flag-of-South-Africa.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            202 => 
            array (
                'id' => 203,
                'code' => 'GS',
                'name' => 'South Georgia',
                'phonecode' => '0',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            203 => 
            array (
                'id' => 204,
                'code' => 'SS',
                'name' => 'South Sudan',
                'phonecode' => '211',
                'flag' => '/flags/flag-of-South-Sudan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            204 => 
            array (
                'id' => 205,
                'code' => 'ES',
                'name' => 'Spain',
                'phonecode' => '34',
                'flag' => '/flags/flag-of-Spain.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            205 => 
            array (
                'id' => 206,
                'code' => 'LK',
                'name' => 'Sri Lanka',
                'phonecode' => '94',
                'flag' => '/flags/flag-of-Sri-Lanka.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            206 => 
            array (
                'id' => 207,
                'code' => 'SD',
                'name' => 'Sudan',
                'phonecode' => '249',
                'flag' => '/flags/flag-of-Sudan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            207 => 
            array (
                'id' => 208,
                'code' => 'SR',
                'name' => 'Suriname',
                'phonecode' => '597',
                'flag' => '/flags/flag-of-Suriname.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            208 => 
            array (
                'id' => 209,
                'code' => 'SJ',
                'name' => 'Svalbard And Jan Mayen Islands',
                'phonecode' => '47',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            209 => 
            array (
                'id' => 210,
                'code' => 'SZ',
                'name' => 'Swaziland',
                'phonecode' => '268',
                'flag' => '/flags/flag-of-Swaziland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            210 => 
            array (
                'id' => 211,
                'code' => 'SE',
                'name' => 'Sweden',
                'phonecode' => '46',
                'flag' => '/flags/flag-of-Sweden.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            211 => 
            array (
                'id' => 212,
                'code' => 'CH',
                'name' => 'Switzerland',
                'phonecode' => '41',
                'flag' => '/flags/flag-of-Switzerland.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            212 => 
            array (
                'id' => 213,
                'code' => 'SY',
                'name' => 'Syria',
                'phonecode' => '963',
                'flag' => '/flags/flag-of-Syria.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            213 => 
            array (
                'id' => 214,
                'code' => 'TW',
                'name' => 'Taiwan',
                'phonecode' => '886',
                'flag' => '/flags/flag-of-Taiwan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            214 => 
            array (
                'id' => 215,
                'code' => 'TJ',
                'name' => 'Tajikistan',
                'phonecode' => '992',
                'flag' => '/flags/flag-of-Tajikistan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            215 => 
            array (
                'id' => 216,
                'code' => 'TZ',
                'name' => 'Tanzania',
                'phonecode' => '255',
                'flag' => '/flags/flag-of-Tanzania.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            216 => 
            array (
                'id' => 217,
                'code' => 'TH',
                'name' => 'Thailand',
                'phonecode' => '66',
                'flag' => '/flags/flag-of-Thailand.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            217 => 
            array (
                'id' => 218,
                'code' => 'TG',
                'name' => 'Togo',
                'phonecode' => '228',
                'flag' => '/flags/flag-of-Togo.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            218 => 
            array (
                'id' => 219,
                'code' => 'TK',
                'name' => 'Tokelau',
                'phonecode' => '690',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            219 => 
            array (
                'id' => 220,
                'code' => 'TO',
                'name' => 'Tonga',
                'phonecode' => '676',
                'flag' => '/flags/flag-of-Tonga.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            220 => 
            array (
                'id' => 221,
                'code' => 'TT',
                'name' => 'Trinidad And Tobago',
                'phonecode' => '1868',
                'flag' => '/flags/flag-of-Trinidad-and-Tobago.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            221 => 
            array (
                'id' => 222,
                'code' => 'TN',
                'name' => 'Tunisia',
                'phonecode' => '216',
                'flag' => '/flags/flag-of-Tunisia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            222 => 
            array (
                'id' => 223,
                'code' => 'TR',
                'name' => 'Turkey',
                'phonecode' => '90',
                'flag' => '/flags/flag-of-Turkey.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            223 => 
            array (
                'id' => 224,
                'code' => 'TM',
                'name' => 'Turkmenistan',
                'phonecode' => '7370',
                'flag' => '/flags/flag-of-Turkmenistan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            224 => 
            array (
                'id' => 225,
                'code' => 'TC',
                'name' => 'Turks And Caicos Islands',
                'phonecode' => '1649',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            225 => 
            array (
                'id' => 226,
                'code' => 'TV',
                'name' => 'Tuvalu',
                'phonecode' => '688',
                'flag' => '/flags/flag-of-Tuvalu.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            226 => 
            array (
                'id' => 227,
                'code' => 'UG',
                'name' => 'Uganda',
                'phonecode' => '256',
                'flag' => '/flags/flag-of-Uganda.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            227 => 
            array (
                'id' => 228,
                'code' => 'UA',
                'name' => 'Ukraine',
                'phonecode' => '380',
                'flag' => '/flags/flag-of-Ukraine.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            228 => 
            array (
                'id' => 229,
                'code' => 'AE',
                'name' => 'United Arab Emirates',
                'phonecode' => '971',
                'flag' => '/flags/flag-of-United-Arab-Emirates.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            229 => 
            array (
                'id' => 230,
                'code' => 'GB',
                'name' => 'United Kingdom',
                'phonecode' => '44',
                'flag' => '/flags/flag-of-United-Kingdom.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            230 => 
            array (
                'id' => 231,
                'code' => 'US',
                'name' => 'United States',
                'phonecode' => '1',
                'flag' => '/flags/flag-of-United-States-of-America.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-07-27 13:05:21',
                'default_currency' => 1,
            ),
            231 => 
            array (
                'id' => 232,
                'code' => 'UM',
                'name' => 'United States Minor Outlying Islands',
                'phonecode' => '1',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            232 => 
            array (
                'id' => 233,
                'code' => 'UY',
                'name' => 'Uruguay',
                'phonecode' => '598',
                'flag' => '/flags/flag-of-Uruguay.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            233 => 
            array (
                'id' => 234,
                'code' => 'UZ',
                'name' => 'Uzbekistan',
                'phonecode' => '998',
                'flag' => '/flags/flag-of-Uzbekistan.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            234 => 
            array (
                'id' => 235,
                'code' => 'VU',
                'name' => 'Vanuatu',
                'phonecode' => '678',
                'flag' => '/flags/flag-of-Vanuatu.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            235 => 
            array (
                'id' => 236,
                'code' => 'VA',
            'name' => 'Vatican City State (Holy See)',
                'phonecode' => '39',
                'flag' => '/flags/flag-of-Vatican-City.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            236 => 
            array (
                'id' => 237,
                'code' => 'VE',
                'name' => 'Venezuela',
                'phonecode' => '58',
                'flag' => '/flags/flag-of-Venezuela.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            237 => 
            array (
                'id' => 238,
                'code' => 'VN',
                'name' => 'Vietnam',
                'phonecode' => '84',
                'flag' => '/flags/flag-of-Vietnam.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            238 => 
            array (
                'id' => 239,
                'code' => 'VG',
            'name' => 'Virgin Islands (British)',
                'phonecode' => '1284',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            239 => 
            array (
                'id' => 240,
                'code' => 'VI',
            'name' => 'Virgin Islands (US)',
                'phonecode' => '1340',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            240 => 
            array (
                'id' => 241,
                'code' => 'WF',
                'name' => 'Wallis And Futuna Islands',
                'phonecode' => '681',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            241 => 
            array (
                'id' => 242,
                'code' => 'EH',
                'name' => 'Western Sahara',
                'phonecode' => '212',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            242 => 
            array (
                'id' => 243,
                'code' => 'YE',
                'name' => 'Yemen',
                'phonecode' => '967',
                'flag' => '/flags/flag-of-Yemen.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            243 => 
            array (
                'id' => 244,
                'code' => 'YU',
                'name' => 'Yugoslavia',
                'phonecode' => '38',
                'flag' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            244 => 
            array (
                'id' => 245,
                'code' => 'ZM',
                'name' => 'Zambia',
                'phonecode' => '260',
                'flag' => '/flags/flag-of-Zambia.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            245 => 
            array (
                'id' => 246,
                'code' => 'ZW',
                'name' => 'Zimbabwe',
                'phonecode' => '263',
                'flag' => '/flags/flag-of-Zimbabwe.jpg',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'default_currency' => 1,
            ),
            246 => 
            array (
                'id' => 247,
                'code' => 'New',
                'name' => 'New',
                'phonecode' => 'New',
                'flag' => 'flags/flag-of-New-57586.png',
                'status' => 0,
                'created_at' => '2022-02-08 21:06:33',
                'updated_at' => '2023-03-08 14:25:54',
                'default_currency' => 1,
            ),
            247 => 
            array (
                'id' => 248,
                'code' => 'New Country',
                'name' => 'New Country',
                'phonecode' => '111',
                'flag' => 'flags/flag-of-New-Country-54339.png',
                'status' => 1,
                'created_at' => '2022-02-08 21:07:21',
                'updated_at' => '2022-02-08 21:07:21',
                'default_currency' => 1,
            ),
        ));
        
        
    }
}